name: 功能请求
description: 提出新功能/增强建议
title: "[Feature] "
labels:
  - enhancement
body:
  - type: textarea
    id: motivation
    attributes:
      label: 需求背景
      description: 你希望解决什么问题？为什么需要？
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 方案描述
      description: 你希望怎么做？是否有参考实现/论文/链接？
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: 影响范围
      description: 预计影响哪些 Pass / 哪些平台 / 是否需要新增测试？
    validations:
      required: false

